### PR TITLE
End-to-end tests

### PR DESCRIPTION
**Pull request by johnny243**
The following PR fixes the following minor bugs:

- 'Export Data' label doesn't change from 'Processing...' when the export process is intentionally interrupted/cancelled (https://github.com/standardnotes/mobile/issues/246)
- 'Sign out' button is still present after signing out

Additionally, end-to-end tests have been introduced into the codebase. Tests for the above changes have been included also.

## How to run end-to-end tests

1. Pull this branch (`e2e-testing`) and run `npm install`
1. Setup an Android emulator and launch it. The `detox` configuration object contains both `android.emu.debug` and `android.emu.release`, which both use a predefined AVD. In this case, a Google Pixel 2 XL was used. You can use a physical device too, but this is out of scope for the present PR :)
1. Run `npx react-native start` to start Metro Bundler.
1. Finally, run `detox test -c android.emu.debug` to start the Standard Notes app. Tests should start running.

e2e-preview_2020-04-02

### Dependencies
- [detox](https://www.npmjs.com/package/detox)
- [mocha](https://www.npmjs.com/package/mocha)
- [faker](https://www.npmjs.com/package/faker)

### CODE REVIEW

**Comment by mobitar** [comment]
This is great! Could you also update the readme with testing instructions?

```
0 passing (2s)
  1 failing

  1) "before all" hook in "{root}":
     Error: '/Users/mo/Desktop/sn/dev/mobile/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk' could not be found, did you run './gradlew assembleAndroidTest' ?
      at EmulatorDriver.getTestApkPath (node_modules/detox/src/devices/drivers/AndroidDriver.js:82:13)
      at EmulatorDriver.installApp (node_modules/detox/src/devices/drivers/AndroidDriver.js:71:77)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Device.prepare (node_modules/detox/src/devices/Device.js:27:7)
      at async Detox.init (node_modules/detox/src/Detox.js:81:5)
      at async Function._initializeInstance (node_modules/detox/src/DetoxExportWrapper.js:89:7)
      at async DetoxExportWrapper.init (node_modules/detox/src/DetoxExportWrapper.js:38:20)
      at async Context.<anonymous> (e2e/init.js:6:3)
```

I had to run `cd android && ./gradlew assembleAndroidTest` to fix this.

Then I tried running `detox test -c android.emu.debug` but got this:

```
detox[76562] INFO:  [DetoxServer.js] server listening on localhost:59526...
detox[76562] ERROR: [exec.js/SPAWN_STDERR, #15] java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{com.standardnotes.test/androidx.test.runner.AndroidJUnitRunner} from pid=6659, uid=6659 not allowed because package com.standardnotes.test does not have a signature matching the target com.standardnotes
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)

detox[76562] ERROR: [exec.js/SPAWN_STDERR, #15] 	at android.app.IActivityManager$Stub$Proxy.startInstrumentation(IActivityManager.java:4501)
	at com.android.commands.am.Instrument.run(Instrument.java:484)
	at com.android.commands.am.Am.runInstrument(Am.java:194)
	at com.android.commands.am.Am.onRun(Am.java:80)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
	at com.android.commands.am.Am.main(Am.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.startInstrumentation(ActivityManagerService.java:22119)
	at android.app.IActivityManager$Stub.onTransact$startInstrumentation$(IActivityManager.java:10316)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:528)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3291)
	at android.os.Binder.execTransact(Binder.java:731)


detox[76562] ERROR: [exec.js/EXEC_FAIL, #17] ""/Users/mo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "ps | grep \"com\.standardnotes$\""" failed with code = 1, stdout and stderr:

detox[76562] ERROR: [exec.js/EXEC_FAIL, #17] 
detox[76562] ERROR: [exec.js/EXEC_FAIL, #17] 
detox[76562] ERROR: [exec.js/EXEC_FAIL, #18] ""/Users/mo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "ps | grep \"com\.standardnotes$\""" failed with code = 1, stdout and stderr:

detox[76562] ERROR: [exec.js/EXEC_FAIL, #18] 
detox[76562] ERROR: [exec.js/EXEC_FAIL, #18] 
detox[76562] ERROR: [exec.js/EXEC_FAIL, #19] ""/Users/mo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "ps | grep \"com\.standardnotes$\""" failed with code = 1, stdout and stderr:

detox[76562] ERROR: [exec.js/EXEC_FAIL, #19] 
detox[76562] ERROR: [exec.js/EXEC_FAIL, #19] 
detox[76562] ERROR: [exec.js/EXEC_FAIL, #20] ""/Users/mo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "ps | grep \"com\.standardnotes$\""" failed with code = 1, stdout and stderr:

detox[76562] ERROR: [exec.js/EXEC_FAIL, #20] 
detox[76562] ERROR: [exec.js/EXEC_FAIL, #20] 
detox[76562] ERROR: [exec.js/EXEC_FAIL, #21] ""/Users/mo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "ps | grep \"com\.standardnotes$\""" failed with code = 1, stdout and stderr:

detox[76562] ERROR: [exec.js/EXEC_FAIL, #21] 
detox[76562] ERROR: [exec.js/EXEC_FAIL, #21] 
detox[76562] ERROR: [DetoxExportWrapper.js/DETOX_INIT_ERROR] 
 DetoxRuntimeError: DetoxRuntimeError: Failed to run application on the device

HINT: Most likely, your main activity has crashed prematurely

Native stacktrace dump: 
    at EmulatorDriver._getInstrumentationCrashError (/Users/mo/Desktop/sn/dev/mobile/node_modules/detox/src/devices/drivers/AndroidDriver.js:175:12)
    at EmulatorDriver.instrumentationCloseListener (/Users/mo/Desktop/sn/dev/mobile/node_modules/detox/src/devices/drivers/AndroidDriver.js:142:67)
    at /Users/mo/Desktop/sn/dev/mobile/node_modules/detox/src/devices/drivers/AndroidDriver.js:143:55
    at new Promise (<anonymous>)
    at EmulatorDriver.waitUntilReady (/Users/mo/Desktop/sn/dev/mobile/node_modules/detox/src/devices/drivers/AndroidDriver.js:141:11)
    at Device.launchApp (/Users/mo/Desktop/sn/dev/mobile/node_modules/detox/src/devices/Device.js:87:29)
    at async Device.prepare (/Users/mo/Desktop/sn/dev/mobile/node_modules/detox/src/devices/Device.js:31:7)
    at async Detox.init (/Users/mo/Desktop/sn/dev/mobile/node_modules/detox/src/Detox.js:81:5)
    at async Function._initializeInstance (/Users/mo/Desktop/sn/dev/mobile/node_modules/detox/src/DetoxExportWrapper.js:89:7)
    at async DetoxExportWrapper.init (/Users/mo/Desktop/sn/dev/mobile/node_modules/detox/src/DetoxExportWrapper.js:38:20)
    at async Context.<anonymous> (/Users/mo/Desktop/sn/dev/mobile/e2e/init.js:6:3)
detox[76562] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = -1000) isReady: {}

Unresponded network requests might result in timeout errors in Detox tests.

  1) "before all" hook in "{root}"

  0 passing (14s)
  1 failing

  1) "before all" hook in "{root}":
     Error: DetoxRuntimeError: Failed to run application on the device

HINT: Most likely, your main activity has crashed prematurely

Native stacktrace dump: 
      at EmulatorDriver._getInstrumentationCrashError (node_modules/detox/src/devices/drivers/AndroidDriver.js:175:12)
      at EmulatorDriver.instrumentationCloseListener (node_modules/detox/src/devices/drivers/AndroidDriver.js:142:67)
      at /Users/mo/Desktop/sn/dev/mobile/node_modules/detox/src/devices/drivers/AndroidDriver.js:143:55
      at new Promise (<anonymous>)
      at EmulatorDriver.waitUntilReady (node_modules/detox/src/devices/drivers/AndroidDriver.js:141:11)
      at Device.launchApp (node_modules/detox/src/devices/Device.js:87:29)
      at async Device.prepare (node_modules/detox/src/devices/Device.js:31:7)
      at async Detox.init (node_modules/detox/src/Detox.js:81:5)
      at async Function._initializeInstance (node_modules/detox/src/DetoxExportWrapper.js:89:7)
      at async DetoxExportWrapper.init (node_modules/detox/src/DetoxExportWrapper.js:38:20)
      at async Context.<anonymous> (e2e/init.js:6:3)
```

The main issue being this:

```
...not allowed because package com.standardnotes.test does not have a signature matching the target com.standardnotes
```

Does the app have to be installed beforehand on the emulator?

**Comment by johnny243** [comment]
> I had to run cd android && ./gradlew assembleAndroidTest to fix this.

Sorry, I missed this. There's a command for that already `detox build -c android.emu.debug`

Are you running this on macOS?

**Comment by johnny243** [comment]
Try clearing the `android/app/build/outputs` directory. Then `detox build -c android.emu.debug` and after `detox test -c android.emu.debug`

**Comment by mobitar** [comment]
Will test this again soon but I think this is good to merge!

**Pull request merged**
