### PR TITLE
Privileges simplification fixes

### PR DESCRIPTION
**Pull request by antsgar**
Fixes:

- No top border present on top of Manage Sessions cell
- Protection authentication screen has awkward spacing in some cells
- Unable to scroll Protection Authentication screen when keyboard is open (Used react-native-keyboard-aware-scroll-view for this as KeyboardAvoidingView combined with ScrollView requires setting an offset for the KeyboardAvoidingView that makes it look different depending on the device. This third-party lib works pretty well for this.)
- Selecting a session from Manage Sessions should show an ActionSheet instead of an alert to revoke the session.
- Removed "Waiting" from authentication task titles as it was redundant with subtitles/placeholders indicating the task is waiting.

### CODE REVIEW

**Comment by antsgar** [comment]
Forgot about the fix/feat/chore commit naming convention, my bad! Old habits die hard. Will make sure I use them next time.

**Comment by mobitar** [comment]
Hmm, react-native-keyboard-aware-scroll-view seems to be abandoned, as it hasn't had a [commit](https://github.com/APSL/react-native-keyboard-aware-scroll-view/commits/master) since Oct 6, 2020. Are we sure this is necessary?

**Comment by antsgar** [comment]
> Hmm, react-native-keyboard-aware-scroll-view seems to be abandoned, as it hasn't had a [commit](https://github.com/APSL/react-native-keyboard-aware-scroll-view/commits/master) since Oct 6, 2020. Are we sure this is necessary?

That's a very good point, I went down this route because I wasn't happy with the way KeyboardAvoidingView was behaving but I'm not too keen on it either. I saw we already have some logic implemented to get the keyboard's height so I wanted to fiddle a bit with that next week and do something custom. If it doesn't work out we can always go with KeyboardAvoidingView even if it's not perfect.

**Review by baptiste-grob — APPROVED** [review]

**Comment by antsgar** [comment]
Reverted the keyboard-aware-scrollview fix for now as I want to work a bit more on it and merge the rest of this PR.

**Pull request merged**
